P3 = python3
default: bubble

bubble:					#run naive program
	$(P3) serialBubble.py

merge:					#run naive program
	$(P3) serialMerge.py

shell:					#run naive program
	$(P3) serialShell.py

bucket:					#run naive program
	$(P3) serialBucket.py