P3 = python3
default: bubble

bubble:					#run serial bubble program
	$(P3) bubble_sort/serialBubble.py

merge:					#run serial merge program
	$(P3) merge_sort/serialMerge.py

shell:					#run serial shell program
	$(P3) shell_sort/serialShell.py

bucket:					#run serial bucket program
	$(P3) bucket_sort/serialBucket.py

pbubble:					#run serial bucket program
	$(P3) bubble_sort/parallelBubble.py

pmerge:					#run serial bucket program
	$(P3) merge_sort/parallelMerge.py

pshell:					#run serial bucket program
	$(P3) shell_sort/parallelShell.py

pbucket:					#run serial bucket program
	$(P3) bucket_sort/parallelBucket.py